label credit:
  scene bg deep
  "..."
  "..."
  "Hello Users and Gamers."
  "I'm glad to see that you enjoyed the game."
  "Sorry to break it to you, but this world is just a demo."
  "A beta version of this is not even out yet."
  "Who am I?"
  "I'm the one that controls this universe."
  "Many names for me to pick one."
  "Anyways, this small world of theirs is nothing compare to what I have in store."
  "If you want to see a better worlds like this, be sure to follow this twitter account @DeadGhoul21."
  "Also there is a man in YouTube who I'm connected with."
  "Goes by the name S1nner, he can tell you about the upcoming projects that we have worked togeher."
  "Can't wait to see you again in another world."